### ISSUE TITLE
[Help] Not downloading 1080p60

### ISSUE THREAD

**Issue by Hirashi3630** [doophack/PrNdOwN#2]
not downloading in 1080p60 (yes the I tried a lot 1080p videos)

as you wrote in README:
> Features
> - Ultra HD Quality (1080,60FPS)
> - CUSTOM SETTINS (Change Your Prefered Quality In PrNdOwN.py)

my conf. in PrNdOwN.py:
```
'Video': {
        'format': 'bestvideo+bestaudio/best',
        'noplaylist': True,
        'postprocessors': [{
            'key': 'FFmpegVideoConvertor',
            'preferedformat': 'mp4',
            #'preferredquality': '137',
        }]
    },
```

Can you help me? btw when uncommenting the `'preferredquality': '137'` it throws error

**Comment by M1ndo** [comment]
> not downloading in 1080p60 (yes the I tried a lot 1080p videos)
> 
> as you wrote in README:
> 
> > Features
> > 
> > * Ultra HD Quality (1080,60FPS)
> > * CUSTOM SETTINS (Change Your Prefered Quality In PrNdOwN.py)
> 
> my conf. in PrNdOwN.py:
> 
> ```
> 'Video': {
>         'format': 'bestvideo+bestaudio/best',
>         'noplaylist': True,
>         'postprocessors': [{
>             'key': 'FFmpegVideoConvertor',
>             'preferedformat': 'mp4',
>             #'preferredquality': '137',
>         }]
>     },
> ```
> 
> Can you help me? btw when uncommenting the `'preferredquality': '137'` it throws error

it's unfortunate to say that it requires premium account to be able to download at 1080p.

**Comment by Hirashi3630** [comment]
> it's unfortunate to say that it requires premium account to be able to download at 1080p.

PH allows watching 1080p without premium as you can see here:

![image](https://user-images.githubusercontent.com/37778278/72216110-f8ef2500-351c-11ea-9c1a-bab9cfdf7cab.png)

**Comment by M1ndo** [comment]
> H allows watching 1080p without premium as you can see here:
Yes But Not downloading At 1080 , It Requires Premium Prescription .
