### ISSUE TITLE
Hown i can download 1080p 60fps or premium videos?

### ISSUE THREAD

**Issue by marcelotk15** [doophack/PrNdOwN#4]
I only received this message: ```ERROR: PornHub Premium requires authentication. You may want to use --cookies.```
I use the flag but nothings happens.

**Comment by M1ndo** [comment]
As I Mentioned In README, Downloading 1080p Video Requires Premium Account .
In Case U Have already an account consider adding username and password in the config inside of PrNdOwN.py.
```
config = {
     .......
    'listformat': {
        'lisformats': True
    },
    'username': 'UR_USERNAME',
    'password':  'UR_PASSWORD',
}
```

**Comment by ovladuk** [comment]
i can't figure out where to put that code in the py file

**Comment by marcelotk15** [comment]
With username and password:
```PornHub said: Upgrade now to enjoy this video Start Your Free Week Already a Premium member? Log in or Sign up```

**Comment by M1ndo** [comment]
> With username and password:
> `PornHub said: Upgrade now to enjoy this video Start Your Free Week Already a Premium member? Log in or Sign up`

Do you already have a premium account?

**Comment by marcelotk15** [comment]
> > With username and password:
> > `PornHub said: Upgrade now to enjoy this video Start Your Free Week Already a Premium member? Log in or Sign up`
> 
> Do you already have a premium account?

Yes!

**Comment by M1ndo** [comment]
> > > With username and password:
> > > `PornHub said: Upgrade now to enjoy this video Start Your Free Week Already a Premium member? Log in or Sign up`
> > 
> > 
> > Do you already have a premium account?
> 
> Yes!

Thank you for your request, I'll review it and push a new update to fix this.
