### ISSUE TITLE
Default download location

### ISSUE THREAD

**Issue by gingerninja85** [doophack/PrNdOwN#5]
Is there a way to change the default download location?

**Comment by i0Ek3** [comment]
@gingerninja85 Here the way: change the python file downloader.py's `os.getcwd()` (line 78: print(get_colors.green() + '[' + get_colors.magento() + '+' + get_colors.green() + ']' + get_colors.white() + ' Folder ' + get_colors.randomize() + os.getcwd())) to your path.

**Comment by M1ndo** [comment]
@gingerninja85 In order to change download location to your preferred, add these lines after ``download.download(link, config['Video'])`` line 240,254,260,266 .
```
src=title+".mp4"
dst="/home/poms/Videos/"  # Linux / Mac Example /home/poms/Videos/ # Windows C:\\Users\\poms\\Videos\\
if os.path.isdir(dst):
       dst=dst+src
       import shutil
       shutil.move(src,dst)
       print(get_colors.green() + '[' + get_colors.magento() + '+' + get_colors.green() + ']' + get_colors.white() + ' File Moved To ' + get_colors.randomize() + dst + get_colors.white()) 
else:
       print(get_colors.green() + '[' + get_colors.magento() + '!!' + get_colors.green() + ']' + get_colors.white() + ' Folder ' + get_colors.randomize() + dst + get_colors.red() + "Does not exist!")
```
